### ISSUE TITLE
Add methodCallback option to be passed to Meteor.call

### ISSUE THREAD

**Issue by craigmaslowski** [copleykj/meteor-shower#40]
Currently, there's no way to specify a callback to be passed to Meteor.call. I propose adding a `methodCallback` option that will be passed to `Meteor.call`.

The most common use case for this is taking a user to a "detail" page where the route needs an `_id` from some doc the user just added.  I'm sure it will be useful in other situations as well.

It should be as simple as changing the call to `Meteor.call` to:

``` JavaScript
Meteor.call(optionsObject.method, formFields, this, optionsObject.methodCallback);
```

I'd actually done this locally, but my change was wiped by the new Atmosphere package, so I finally took some time to submit this issue.

``` JavaScript
// usage example
Mesosphere({
  name: 'addPost',
  template: 'addPost',
  method: 'addPost',
  methodCallback: function (postId) { 
    Router.go('postDetail', {_id: postId});
  },
  fields: ...
```

**Comment by gcacars** [comment]
You should do:
    // usage example
    Mesosphere({
      name: 'addPost',
      template: 'addPost',
      method: function( data ){
        Meteor.call('addPost', data, function(){
            // callback function
        }
      }
      fields: ...
