### ISSUE TITLE
Is i18n(internationalization) applicable in this package

### ISSUE THREAD

**Issue by naoziwatele** [copleykj/meteor-shower#65]
Is it possible to have the returned message in different languages?

**Comment by copleykj** [comment]
In it's current form it is not. I personally haven't been doing validation this way since I started using aldeed:simple-schema. Its a much more meteoric way of doing validation and allows you to secure your writes in such a way to allow you to do all database operations from the client.

**Comment by copleykj** [comment]
You are of course more than welcome to for and modify the repo if you prefer this type of validation.
